### ISSUE TITLE
Terminal always starts with root directory rather than opened project root directory when open with cli command

### ISSUE THREAD

**Issue by WindSoilder** [zed-industries/feedback#847]
### Check for existing issues

- [X] Completed

### Describe the bug / provide steps to reproduce it

1. open zed editor with cli command `zed .`
2. press `shift+esc` to open dock
3. and we can see that the terminal's current directory is root, I would expect the terminal's current directory is project root directory

![img](https://user-images.githubusercontent.com/22256154/211441595-eccbcc30-cea6-47f1-af43-e118e86fddad.png)

### Environment

Zed 0.67.5 – /Applications/Zed.app \nmacOS 13.0.1 \narchitecture x86_64

**Comment by ethanwood17** [comment]
I also find this occurs if I am re-opening a project. If I had a project open with a terminal in a tab, and then close the entire window, when I reopen the project my open files are restored, but the terminal tab will have navigated to my root directory instead of wherever it was previously.

**Comment by JosephTLyons** [comment]
Hey @ethanwood17, this should be resolved in v0.69.0.

**Comment by WindSoilder** [comment]
Hi, it seems that the issue is not fixed.

If I open with `zed .`, and open a terminal in a tab, it works, but if I "Focus Dock", it still starts with root directory.

**Comment by Kethku** [comment]
Have you opened that directory before? Workspace persistence might be restoring the terminal with the wrong location.

You can avoid this by intentionally closing the dock terminal (which will close the dock if it is the sole remaining item in it) and reopening it with "focus dock"

**Comment by WindSoilder** [comment]
https://user-images.githubusercontent.com/22256154/213317538-4d9b325d-5a48-4c88-b9b9-08ac78d6560e.mov

It seems that it happened when we have opened that directory before.

**Comment by mikayla-maki** [comment]
Hi @WindSoilder, this should be fixed by the next release :)

**Comment by WindSoilder** [comment]
Thanks for all your effort!  It really bothers me for a long time :-D
